services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: always
    environment:
      - CF_DNS_API_TOKEN=cfut_iPM6zAKbi4EtU7QFDzsGprOG6aL58cdiRUqA9Hum4faee69d
      - DOCKER_API_VERSION=1.40
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./acme.json:/acme.json
    networks:
      - red-traefik

networks:
  red-traefik:
    external: true
